-- SELECT * FROM tm_insumo AS i WHERE i.tm_nombre IN (
-- 'acelga',
-- 'ají amarillo',
-- 'ají cerezo',
-- 'apio',
-- 'arvejas',
-- 'arvejas secas',
-- 'avena',
-- 'brócoli',
-- 'camote',
-- 'camote amarillo',
-- 'camote morado',
-- 'col',
-- 'coliflor',
-- 'espinaca',
-- 'fréjol',
-- 'fréjol bayo',
-- 'fréjol canario',
-- 'fréjol verde',
-- 'frejoles panamitos',
-- 'frejoles verdes',
-- 'haba',
-- 'habas secas',
-- 'habas verdes',
-- 'lentejas',
-- 'pallares',
-- 'poro',
-- 'quinua',
-- 'zapallo',
-- 'zapallo loche',
-- 'zapallo macre',
-- 'zanahoria') ORDER BY i.tm_nombre;

SELECT * FROM tm_insumo WHERE td_carbohidratos <= 57

SELECT * FROM tm_insumo WHERE tm_nombre IN (
'aceite de ajonjolí',
'aceite de albahaca',
'aceite de olivas',
'aceite vegetal',
'aceituna negra',
'aceituna verde',
'ajo',
'alcaparras',
'almeja',
'angostura (amargo)',
'anchoa',
'apio',
'arvejas secas',
'atún',
'avellana',
'bacón',
'berenjena',
'bistec de carne de res',
'bistec de res',
'bistecs de hígado de res',
'bofe de res',
'brócoli',
'cabrito',
'calamares',
'camarón',
'camarón entero',
'carne de cerdo',
'carne de cordero',
'carne de gallina',
'carne de res',
'carne de venado',
'carne molida',
'carnes frías',
'carnero',
'cecina',
'cerdo',
'champiñones',
'chancho',
'charqui',
'chonta',
'chorizo regional',
'chuño',
'chuño negro',
'clara de huevo',
'col',
'coliflor',
'corazón de pollo',
'corazón de res',
'corvina',
'costilla de cerdo ahumada',
'costillar',
'criadilla',
'cuy',
'diente de león',
'doncellas',
'eneldo fresco',
'espinaca',
'extracto de camarón',
'fettuccine',
'filete de carne de res',
'filete de pescado',
'filete de pollo',
'fresco',
'frutos secos',
'garbanzos',
'grasas saludables',
'haba',
'habas secas',
'habas verdes',
'harina de maíz',
'harina de trigo',
'hierba luisa filtrante',
'hierbabuena',
'hoja de laurel',
'hojas de bijao',
'hojas de hierbabuena',
'hojas de laurel',
'hojas de lechuga',
'huevo',
'jamón',
'jamón serrano',
'jengibre',
'kion',
'láminas de pasta',
'langostinos',
'lardo',
'laurel',
'lechuga',
'lechuga orgánica',
'lenguado',
'licor triple seco',
'limón',
'loche',
'longaniza calabresa',
'lomo',
'lomo fino',
'lomo saltado',
'lomo vetado',
'lúcuma',
'mantequilla',
'mariscos',
'masa para pizza',
'mayonesa',
'mero',
'molleja de pollo',
'mondongo de res',
'morrones',
'muña',
'nueces',
'orégano',
'ossobuco',
'paico',
'palmitos',
'palta',
'panceta',
'panceta de cerdo',
'papaya',
'pasas',
'pasta fresca',
'pata de cerdo',
'pata de res',
'pato',
'pecanas',
'pechuga de pavo',
'pechuga de pollo',
'perejil',
'pescado',
'pescado blanco',
'pescado doncella',
'pescado guitarra',
'pescado seco',
'pimienta',
'pimiento rojo',
'pimiento verde',
'piña',
'plátano maduro',
'pollo',
'pulpo',
'queso asadero',
'queso de cabra',
'queso fontin',
'queso fresco',
'queso mantecoso',
'queso mozzarella',
'queso parmesano',
'queso provolone',
'queso ricota',
'quinua',
'rachi',
'raya',
'remolacha',
'res',
'rocoto',
'romero',
'salame',
'salchichas',
'salmón',
'sardinas',
'salsa criolla',
'sardinas',
'tomate',
'tocino',
'tocino picado',
'tocino trozado',
'tomillo',
'trucha',
'uvas',
'vainilla',
'vinagre',
'vinagre balsámico',
'vinagre blanco',
'vinagre rojo',
'vodka',
'yuca',
'zanahoria',
'zapallo',
'zapallo loche',
'zapallo macre'
);

